// AUTH
export const AUTH_IS_BUSY = 'AUTH_IS_BUSY';
export const AUTH_IS_FREE = 'AUTH_IS_FREE';
export const AUTH_STORE = 'AUTH_STORE';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_DESTROY = 'AUTH_DESTROY';
export const AUTH_IS_ERROR = 'AUTH_IS_ERROR';
export const AUTH_IS_ERROR_FREE = 'AUTH_IS_ERROR_FREE';

// OUTLETS
export const OUTLETS_IS_BUSY = 'OUTLETS_IS_BUSY';
export const OUTLETS_IS_FREE = 'OUTLETS_IS_FREE';
export const OUTLETS_INDEX = 'OUTLETS_INDEX';
export const OUTLETS_STORE = 'OUTLETS_STORE';
export const OUTLETS_UPDATE = 'OUTLETS_UPDATE';
export const OUTLETS_DESTROY = 'OUTLETS_DESTROY';
export const OUTLETS_IS_ERROR = 'OUTLETS_IS_ERROR';
export const OUTLETS_IS_ERROR_FREE = 'OUTLETS_IS_ERROR_FREE';

// LOTTERIES
export const LOTTERIES_IS_BUSY = 'LOTTERIES_IS_BUSY';
export const LOTTERIES_IS_FREE = 'LOTTERIES_IS_FREE';
export const LOTTERIES_INDEX = 'LOTTERIES_INDEX';
export const LOTTERIES_STORE = 'LOTTERIES_STORE';
export const LOTTERIES_UPDATE = 'LOTTERIES_UPDATE';
export const LOTTERIES_DESTROY = 'LOTTERIES_DESTROY';
export const LOTTERIES_IS_ERROR = 'LOTTERIES_IS_ERROR';
export const LOTTERIES_IS_ERROR_FREE = 'LOTTERIES_IS_ERROR_FREE';

// PRIZES
export const PRIZES_IS_BUSY = 'PRIZES_IS_BUSY';
export const PRIZES_IS_FREE = 'PRIZES_IS_FREE';
export const PRIZES_INDEX = 'PRIZES_INDEX';
export const PRIZES_DESTROY = 'PRIZES_DESTROY';
export const PRIZES_IS_ERROR = 'PRIZES_IS_ERROR';
export const PRIZES_IS_ERROR_FREE = 'PRIZES_IS_ERROR_FREE';

// USERS
export const USERS_IS_BUSY = 'USERS_IS_BUSY';
export const USERS_IS_FREE = 'USERS_IS_FREE';
export const USERS_INDEX = 'USERS_INDEX';
export const USERS_STORE = 'USERS_STORE';
export const USERS_UPDATE = 'USERS_UPDATE';
export const USERS_DESTROY = 'USERS_DESTROY';
export const USERS_IS_ERROR = 'USERS_IS_ERROR';
export const USERS_IS_ERROR_FREE = 'USERS_IS_ERROR_FREE';

// REVIEWS
export const REVIEWS_IS_BUSY = 'REVIEWS_IS_BUSY';
export const REVIEWS_IS_FREE = 'REVIEWS_IS_FREE';
export const REVIEWS_INDEX = 'REVIEWS_INDEX';
export const REVIEWS_STORE = 'REVIEWS_STORE';
export const REVIEWS_UPDATE = 'REVIEWS_UPDATE';
export const REVIEWS_DESTROY = 'REVIEWS_DESTROY';
export const REVIEWS_IS_ERROR = 'REVIEWS_IS_ERROR';
export const REVIEWS_IS_ERROR_FREE = 'REVIEWS_IS_ERROR_FREE';

// BANNERS
export const BANNERS_IS_BUSY = 'BANNERS_IS_BUSY';
export const BANNERS_IS_FREE = 'BANNERS_IS_FREE';
export const BANNERS_INDEX = 'BANNERS_INDEX';
export const BANNERS_STORE = 'BANNERS_STORE';
export const BANNERS_UPDATE = 'BANNERS_UPDATE';
export const BANNERS_DESTROY = 'BANNERS_DESTROY';
export const BANNERS_IS_ERROR = 'BANNERS_IS_ERROR';
export const BANNERS_IS_ERROR_FREE = 'BANNERS_IS_ERROR_FREE';

// IMAGES
export const IMAGES_IS_BUSY = 'IMAGES_IS_BUSY';
export const IMAGES_IS_FREE = 'IMAGES_IS_FREE';
export const IMAGES_INDEX = 'IMAGES_INDEX';
export const IMAGES_STORE = 'IMAGES_STORE';
export const IMAGES_UPDATE = 'IMAGES_UPDATE';
export const IMAGES_DESTROY = 'IMAGES_DESTROY';
export const IMAGES_IS_ERROR = 'IMAGES_IS_ERROR';
export const IMAGES_IS_ERROR_FREE = 'IMAGES_IS_ERROR_FREE';

// ADS
export const ADS_IS_BUSY = 'ADS_IS_BUSY';
export const ADS_IS_FREE = 'ADS_IS_FREE';
export const ADS_INDEX = 'ADS_INDEX';
export const ADS_STORE = 'ADS_STORE';
export const ADS_UPDATE = 'ADS_UPDATE';
export const ADS_DESTROY = 'ADS_DESTROY';
export const ADS_IS_ERROR = 'ADS_IS_ERROR';
export const ADS_IS_ERROR_FREE = 'ADS_IS_ERROR_FREE';
