// SIDEBAR
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
export const SIDEBAR_SHOW = 'SIDEBAR_SHOW';
export const SIDEBAR_HIDE = 'SIDEBAR_HIDE';

// AUTH
export const AUTH_IS_BUSY = 'AUTH_IS_BUSY';
export const AUTH_IS_FREE = 'AUTH_IS_FREE';
export const AUTH_STORE = 'AUTH_STORE';
export const AUTH_UPDATE = 'AUTH_UPDATE';
export const AUTH_DESTROY = 'AUTH_DESTROY';
export const AUTH_IS_ERROR = 'AUTH_IS_ERROR';
export const AUTH_IS_ERROR_FREE = 'AUTH_IS_ERROR_FREE';
export const AUTH_OTP_IS_SEND = 'AUTH_OTP_IS_SEND';
export const AUTH_OTP_IS_VERIFIED = 'AUTH_OTP_IS_VERIFIED';
export const AUTH_OTP_RESET = 'AUTH_OTP_RESET';

// OUTLETS
export const OUTLETS_IS_BUSY = 'OUTLETS_IS_BUSY';
export const OUTLETS_IS_FREE = 'OUTLETS_IS_FREE';
export const OUTLETS_INDEX = 'OUTLETS_INDEX';
export const OUTLETS_IS_ERROR = 'OUTLETS_IS_ERROR';
export const OUTLETS_IS_ERROR_FREE = 'OUTLETS_IS_ERROR_FREE';

// LOTTERIES
export const LOTTERIES_IS_BUSY = 'LOTTERIES_IS_BUSY';
export const LOTTERIES_IS_FREE = 'LOTTERIES_IS_FREE';
export const LOTTERIES_INDEX = 'LOTTERIES_INDEX';
export const LOTTERIES_IS_ERROR = 'LOTTERIES_IS_ERROR';
export const LOTTERIES_IS_ERROR_FREE = 'LOTTERIES_IS_ERROR_FREE';

// USERS
export const USERS_IS_BUSY = 'USERS_IS_BUSY';
export const USERS_IS_FREE = 'USERS_IS_FREE';
export const USERS_INDEX = 'USERS_INDEX';
export const USERS_STORE = 'USERS_STORE';
export const USERS_UPDATE = 'USERS_UPDATE';
export const USERS_DESTROY = 'USERS_DESTROY';
export const USERS_IS_ERROR = 'USERS_IS_ERROR';
export const USERS_IS_ERROR_FREE = 'USERS_IS_ERROR_FREE';

// REVIEWS
export const REVIEWS_IS_BUSY = 'REVIEWS_IS_BUSY';
export const REVIEWS_IS_FREE = 'REVIEWS_IS_FREE';
export const REVIEWS_INDEX = 'REVIEWS_INDEX';
export const REVIEWS_STORE = 'REVIEWS_STORE';
export const REVIEWS_UPDATE = 'REVIEWS_UPDATE';
export const REVIEWS_DESTROY = 'REVIEWS_DESTROY';
export const REVIEWS_IS_ERROR = 'REVIEWS_IS_ERROR';
export const REVIEWS_IS_ERROR_FREE = 'REVIEWS_IS_ERROR_FREE';

// BANNERS
export const BANNERS_IS_BUSY = 'BANNERS_IS_BUSY';
export const BANNERS_IS_FREE = 'BANNERS_IS_FREE';
export const BANNERS_INDEX = 'BANNERS_INDEX';
export const BANNERS_IS_ERROR = 'BANNERS_IS_ERROR';
export const BANNERS_IS_ERROR_FREE = 'BANNERS_IS_ERROR_FREE';

// ADS
export const ADS_IS_BUSY = 'ADS_IS_BUSY';
export const ADS_IS_FREE = 'ADS_IS_FREE';
export const ADS_INDEX = 'ADS_INDEX';
export const ADS_IS_ERROR = 'ADS_IS_ERROR';
export const ADS_IS_ERROR_FREE = 'ADS_IS_ERROR_FREE';;

